
package fortegroup.internship.mandrik.docstorage.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DocumentStorageService", targetNamespace = "http://service.docstorage.mandrik.internship.fortegroup/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocumentStorageService {


    /**
     * 
     * @param documentDetails
     * @param uploadDocumentHandler
     * @return
     *     returns fortegroup.internship.mandrik.docstorage.service.Status
     */
    @WebMethod
    @WebResult(name = "status", partName = "status")
    public Status uploadDocument(
        @WebParam(name = "uploadDocumentHandler", partName = "uploadDocumentHandler")
        byte[] uploadDocumentHandler,
        @WebParam(name = "documentDetails", partName = "documentDetails")
        DocumentDetails documentDetails);

    /**
     * 
     * @param documentDetails
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(name = "dataHandler", partName = "dataHandler")
    public byte[] downloadDocument(
        @WebParam(name = "documentDetails", partName = "documentDetails")
        DocumentDetails documentDetails);

    /**
     * 
     * @param documentDetails
     * @return
     *     returns fortegroup.internship.mandrik.docstorage.service.Status
     */
    @WebMethod
    @WebResult(name = "status", partName = "status")
    public Status deleteDocument(
        @WebParam(name = "documentDetails", partName = "documentDetails")
        DocumentDetails documentDetails);

    /**
     * 
     * @param newDocumentDetails
     * @param oldDocumentDetails
     * @return
     *     returns fortegroup.internship.mandrik.docstorage.service.Status
     */
    @WebMethod
    @WebResult(name = "status", partName = "status")
    public Status updateDocument(
        @WebParam(name = "oldDocumentDetails", partName = "oldDocumentDetails")
        DocumentDetails oldDocumentDetails,
        @WebParam(name = "newDocumentDetails", partName = "newDocumentDetails")
        DocumentDetails newDocumentDetails);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "path", partName = "path")
    public String getPathToStorage();

}
